spring.application.name=smartcampus

# connexion to the mysql DB
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus
spring.datasource.username=root
spring.datasource.password=password

# FLYWAY
spring.flyway.default-schema=smartcampus